### PR TITLE
feat(threading): DTT-10: 1 -> 8 threads

### PR DESCRIPTION
**Pull request by millerjs**
Addresses [DTT-10](https://jira.opensciencedatacloud.org/browse/DTT-10).

Updates the client to use 8 threads by default.

### CODE REVIEW

**Comment by christiandompierre** [comment]
+1

**Comment by dankolbman** [comment]
lgtm 👍

**Comment by allisonheath** [comment]
I'm slightly of the opinion the default should be `min(cpu_count()-1, 8)`

**Pull request merged**
